### ISSUE TITLE
Multi-touch drag can bork the game

### ISSUE THREAD

**Issue by xxxserxxx** [billthefarmer/gridle#12]
The game board can be "permanently" mangled by using multi-touch. When this happens, letter spaces are permanently lost and even a new game refresh starts a new game, but with the mangled letter spaces missing. The only fix is to force-stop the app and restart it.

To recreate, start dragging one letter, and while holding, begin dragging a second letter. When the letters are dropped, only the second is moved, and the first letter (and its letter space) are lost. Sometimes, Gridle will stack the first letter on another space, but in any case, the first letter will never again be accessible, and letters will not be drop-able on the first letter's space.

Attached are some screenshots of the board after doing this a few times; the last image shows that starting a new game does not restore the borked spaces.

![Screenshot_20230624_105638_Gridle](https://github.com/billthefarmer/gridle/assets/60757196/9ac06e4e-e245-4b36-8795-87bee7de6b35)
![Screenshot_20230624_105713_Gridle](https://github.com/billthefarmer/gridle/assets/60757196/25545f43-966f-40a4-8bc8-fbeafcc0c09a)
![Screenshot_20230624_105734_Gridle](https://github.com/billthefarmer/gridle/assets/60757196/31ee901b-104f-4a0d-ab35-46d36d182724)
![Screenshot_20230624_110050_Gridle](https://github.com/billthefarmer/gridle/assets/60757196/a014b47b-5727-47c2-85e2-93e16c32292e)

OS/platform: Galaxy Z Flip3; Android 13   
Gridle version: v1.12 from f-droid

**Comment by billthefarmer** [comment]
Rotating the device will restore the display. I will disable multi touch.

**Comment by xxxserxxx** [comment]
> Rotating the device will restore the display. I will disable multi touch.

The one thing I didn't try. Thank you.
