### ISSUE TITLE
Feature request: ask before exiting while pressing back 

### ISSUE THREAD

**Issue by glemco** [billthefarmer/gridle#14]
First of all, thanks for the nice game.
I have a suggestion: it happens quite often (especially with the large grid) that while moving a tile from am edge I trigger the device back gesture. This brings me without any confirmation to the small grid (which is again rather odd but I see it was probably easier to code).
It would be nice to have a confirmation (like _would you really like to exit_ or _press back twice to exit_) on both grids, to avoid this kind of issue, especially on devices with gestures.

**Comment by billthefarmer** [comment]
Yes I agree, it's annoying. There's an API for stopping system gestures interfering with your app by limiting the area. I shall implement that.

**Comment by glemco** [comment]
Sounds good, thank you!

**Comment by billthefarmer** [comment]
OK, there are limitations  on the size of the disabled area, so it only covers most of the grid. The app will also ignore back gestures while a game is in progress &ndash; move count not zero and grid not solved. See [README](https://github.com/billthefarmer/gridle#system-gestures).

**Comment by glemco** [comment]
Great, looks neat :+1:
