### ISSUE TITLE
Feature request: move counter / timer

### ISSUE THREAD

**Issue by vi** [billthefarmer/gridle#2]
Unlike "Gurgle", this game does not provide easy indication of user performance. A move counter (global and/or per-tile) and timer would make comparisons easier.

**Comment by billthefarmer** [comment]
I tried that. I took it out when it took me 37 moves to solve one. I also put the four corner and centre greens in as per the original to make it easier.

**Comment by vi** [comment]
> I took it out when it took me 37 moves to solve one.

I don't think just counting moves (starting from 0 and going up, without any limit) and time (also starting from 0 second and counting up) would annoy users too much. Ideally the game should also keep statistics.

> I also put the four corner and centre greens in as per the original to make it easier.

It may be [too easy](https://github.com/billthefarmer/gridle/issues/4) now. Maybe multiple difficulty mode can be useful?
I think any Girdle can be solved rather quickly by just moving non-green tiles at random, so excess difficulty is probably not a concern.

**Comment by billthefarmer** [comment]
OK, I've put it back in in the latest version.
