### ISSUE TITLE
Just tapping on a tile should not swap it with a neighbour.

### ISSUE THREAD

**Issue by vi** [billthefarmer/gridle#5]
Single tapping a tile (without drag and drop) should not randomish-ly swap it with some neighbouring tile.
It should leave a tile highlighted, so that second tap would select the second tile to swap with.

**Comment by billthefarmer** [comment]
Just tapping on a tile should do nothing. That's in the next version.

**Comment by vi** [comment]
Just tapping on a tile (especially multiple times) should at least show a message that you are supposed to drag them around to swap them.

When user launches the app for the first time, it is not obvious what needs to be done to play the game.

**Comment by billthefarmer** [comment]
RTFRM How to use the app is in the [README](https://github.com/billthefarmer/gridle#readme), built in help and the F-Droid app description. From comments that appear in the issues on my apps, some users seem to avoid reading READMEs, app help, etc.

**Comment by vi** [comment]
> From comments that appear in the issues on my apps, some users seem to avoid reading READMEs, app help, etc.

It is the norm as far as I know. Having app documentation decreases the number of users needing help, but does not prevent it.
Good UX (which also involves showing the helpful messages exactly at the time user may be interested in them, e.g. when user cannot move a tile in the game, not when installing the app) is still needed, even if the app is documented.

> Move letters in the grid to make a gridle of words. It's a good idea to use ... stylus ... stubby fingers ...

This description suits both drag&drop style of interaction and tap-one-then-tap-another style. AFAIR most chess apps use the latter style (or support both), so users may expect other games to work similarly.

Even if the description would specifically mention dragging and dropping, user may forget that after going from installation screen to the game itself, especially those events are far apart. "Help" menu item helps though.

**Comment by billthefarmer** [comment]
Not bothering to read the docs is fine, I do it all the time. Not bothering to read the docs before raising issues is time wasting.

I care fully avoid a drag and drop description because that is used by the android API for something completely different. Tapping on a tile once the grid is solved will now show the meaning of that word if the tile uniquely defines it.

**Comment by vi** [comment]
Gurgle shows "Guess the word first" if I tap on the cells before solving the word.

Similarly, Gridle can show "Solve the grid first by dradding cells around to swap them" toast message if cells are tapped on before solving the word or the grid.
