### ISSUE TITLE
Feature request: Get the meaning for all found words

### ISSUE THREAD

**Issue by bovergaauw** [billthefarmer/gridle#6]
Would it be possible to add the Gurge-type functionality of getting the meaning of each found word for example by clicking on unique letters of that word? This would be a great language learning feature that you apparently developed for Gurgle already.

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

**Comment by bovergaauw** [comment]
Thanks for having added this great feature to Gridle! As with Gurdle, it will make Gridle even more addictive to me 😊. Unlike Gurgle, words don't scroll out of screen, so there's no need to make it possible to check the meaning of correctly guessed words prior to having solved the puzzle, so I'm closing this issue.
