### ISSUE TITLE
REQ: Full palette control

### ISSUE THREAD

**Issue by sanctimoniousape** [billthefarmer/gridle#9]
Game only allows selecting colors for highlighted letters.  I keep screen very dark to save power on OLED, but this makes the grey letters very difficult to see.  Would you please consider adding at least control of those letters, if not the entire palette?

Thanks so much!

**Comment by billthefarmer** [comment]
OK, that's in the next version.

**Comment by sanctimoniousape** [comment]
Fantastic!  Thank you!
